### PR TITLE
update: jsonschema version

### PR DESCRIPTION
**Pull request by aryabharat**
Removed jsonschema refResolver (deprecated in latest version).
Work in progress

### CODE REVIEW

**Comment by clenk** [comment]
Did the tests pass for you when you ran `tox`? I'm getting a bunch of errors when I try it. For example:
> FAILED stix2validator/test/v21/vulnerability_tests.py::VulnerabilityTestCases::test_wellformed_vulnerability - jsonschema.exceptions._RefResolutionError: unknown url type: '../common/core.json'

Does it need a `retrieve` function to be able to pull in referenced schemas like core.json, as [described here](https://python-jsonschema--1049.org.readthedocs.build/en/1049/referencing/#resolving-references-from-the-file-system)?

Also looks like you removed the only usages of the `SCHEMA_STORE` variable, so if we don't need it to fix the RefResolutionErrors then the other 2 mentions of `SCHEMA_STORE` should be removed as well.

**Comment by rpiazza** [comment]
Please merge in the latest from master - we have updated the python versions.

**Comment by rpiazza** [comment]
Please look in the setup.py file to make sure the jsonschema version you need is specified.

**Comment by aryabharat** [comment]
> Did the tests pass for you when you ran `tox`? I'm getting a bunch of errors when I try it. For example:
> 
> > FAILED stix2validator/test/v21/vulnerability_tests.py::VulnerabilityTestCases::test_wellformed_vulnerability - jsonschema.exceptions._RefResolutionError: unknown url type: '../common/core.json'
> 
> Does it need a `retrieve` function to be able to pull in referenced schemas like core.json, as [described here](https://python-jsonschema--1049.org.readthedocs.build/en/1049/referencing/#resolving-references-from-the-file-system)?
> 
> Also looks like you removed the only usages of the `SCHEMA_STORE` variable, so if we don't need it to fix the RefResolutionErrors then the other 2 mentions of `SCHEMA_STORE` should be removed as well.

Was getting few while running test locally, will try again and fix it.
Thanks @rpiazza @clenk

**Comment by clenk** [comment]
I haven't tried it out, but it seems like maybe we could use the `retrieve` option (https://python-jsonschema--1049.org.readthedocs.build/en/1049/referencing/#resolving-references-from-the-file-system) and write a function that will detect when the ref starts with `../` and pull it in from the correct place on the filesystem?

**Comment by clenk** [comment]
@aryabharat Were you able to make any progress? If not I might be able to devote some time to try fixing the tests on my end.

**Comment by aryabharat** [comment]
@clenk Please let me know if you haven not picked it, so will try to continue.

**Comment by ostefano** [comment]
It's actually weird because I see that the pipelines report no errors but however I try the tests locally (OSX, new environment) I see errors. I have tried using `tox` but also with a clean venv:
```
python3 -m venv venv
source venv/bin/activate
pip install -e '.[test]'
./venv/bin/pytest -x
```

**Comment by ostefano** [comment]
@clenk I managed to get the external references working, but I still have failures when the references are now pointing to the schema itself for some reason

```
FAILED stix2validator/test/v20/marking_definition_tests.py::MarkingDefinitionTestCases::test_granular_marking_circular_ref - jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: 'definitions/statement'
```

Will keep investigating but any help appreciated

**Comment by clenk** [comment]
I'm also looking into it, but running into issues with how [jsonschema/referencing ](https://github.com/python-jsonschema/referencing/) is handling $refs/URIs. Would be curious to what you did, @ostefano.

**Comment by ostefano** [comment]
I think I made progress, all tests are now passing.

Will open a new PR soon.

**Comment by ostefano** [comment]
@clenk see here: https://github.com/oasis-open/cti-stix-validator/pull/228

**Comment by ostefano** [comment]
This is not necessary anymore since https://github.com/oasis-open/cti-stix-validator/pull/228 got merged

**Comment by adulau** [comment]
Thank you for the contribution and input. It was fixed in #228

**Pull request closed without merging**
