### PR TITLE
Add debug msg for which schema validates extension

### PR DESCRIPTION
**Pull request by clenk**

### CODE REVIEW

**Comment by rpiazza** [comment]
LGTM, except the -U thing :-)

**Comment by ejratl** [comment]
I fixed the -U problem. The tests when restarted use the version of the GitHub Actions that were in effect at the time of the pull request.

**Comment by ejratl** [comment]
@clenk Do you have any thoughts on why the tests are sometimes failing (as in the Python 3.7 Build (pull_request)). The tests look deterministic to me and correct. I ran into this yesterday too and restarting the failed tests caused it to go away. Can there be a timing issue with multiple simultaneous test runs?

**Comment by clenk** [comment]
@ejratl yeah, that's possible. The tests in question make use of the requests_cache dependency when pulling the list of allowed values from various IANA registries. I wonder if that has something to do with it.

**Pull request merged**
