### PR TITLE
Add option to silence output

### PR DESCRIPTION
**Pull request by StephenThomson**

### CODE REVIEW

**Comment by gtback** [comment]
Thanks, @StephenThomson !

Looks like Travis-CI is just complaining about a couple style issues, should be pretty easy to fix.

Also, you'll need to sign a [Contributor License Agreement](https://www.oasis-open.org/resources/open-repositories/cla) before this can be merged in.

**Comment by StephenThomson** [comment]
Hi Greg,

I've fixed the style issues. Now just waiting on my organisation to give the go ahead to sign the CLA.

I've also have a fork of the elevator with the changes needed to support this new functionality ready. Once this is merged to stable I'll create a pull request for that too.

Thanks,

Steve

**Comment by gtback** [comment]
Thanks for the update, @StephenThomson !

**Comment by StephenThomson** [comment]
Hi,

I've now signed a CLA.

Thanks,

Steve

**Comment by robincover** [comment]
Thanks for contributions, Steve.  See email from me (CLA confirmation request message) - Robin Cover

**Comment by gtback** [comment]
Thanks, @StephenThomson. Merging now 😀

**Pull request merged**
